### ISSUE TITLE
Benchmarking code does not work out of the box

### ISSUE THREAD

**Issue by mjethani** [cliqz-oss/adblocker#110]
The current version of the benchmarking code (in particular the code in `bench/comparison`) does not work without modifications to the makefile.

I had to make the following changes to `bench/comparison/Makefile` to make it work:

1.  Change `git://` URLs to `https://` URLs
2.  Add a rule for the target `adblockpluscore`, which clones `github.com/adblockplus/adblockpluscore` and checks out a specific commit
3.  Replace `requests.json` with `../dataset/requests.json`

**Comment by remusao** [comment]
Hey @mjethani,

Thanks for taking the time to look into it. I have to admit I did not check the setup "from scratch" after the latest changes. It would be nice to also have the Makefile download the dataset so that you only have to run `make` after cloning for everything to work. I will try and find time to fix this soon, or if you already have the changes ready on your side, feel free to open a pull request with the changes.
