### ISSUE TITLE
Getting dom blocked

### ISSUE THREAD

**Issue by dud3** [cliqz-oss/adblocker#1458]
How do we get dom blocked ads?

![image](https://user-images.githubusercontent.com/5823644/99865650-7bb82600-2bab-11eb-9618-98e1036e6cde.png)

Or more specifically, how would we get the dom blocked ads from the following example: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts

Thank you.

**Comment by remusao** [comment]
Hi @dud3,

Blocking DOM ads can be achieve by cosmetic filtering (a.k.a. element hiding, but scriptlet injections also fall in this category). This is supported out of the box by this library. Could you share more details about how you use it in your project (which lists, etc.), and ideally a snippet of code so that I can reproduce.

If you noticed ads not blocked by running https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts locally, can you maybe point me to an example of website where that happens?

Best,
Rémi

**Comment by dud3** [comment]
Hi Rémi,

What I'm trying to create is module that will rank sites based on different type of ads and tackers is containes.

Currently my code is almost identical to: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts

I want to map the info from events to the image below, categorize them as xhr, dom, image, media...

![image](https://user-images.githubusercontent.com/5823644/99881389-d9835700-2c19-11eb-8a8c-cc2478c557c2.png)

Here's an example that runs on a server located in digitalocean (us): http://64.227.14.199/ using your puppeteer example, the result come from the `request-blocked` event only, so that might be the case why it different from ublock chrome extension running on my chrome.

**Comment by dud3** [comment]
Example of my dummy program:

![image](https://user-images.githubusercontent.com/5823644/99881592-ece2f200-2c1a-11eb-93f4-317548887f22.png)

**Comment by dud3** [comment]
@remusao In summary I'm getting the types now, but not the `dom` type.

![image](https://user-images.githubusercontent.com/5823644/99945055-3eeb5b00-2d74-11eb-90fb-dea35e2e6292.png)

Which of the following events returns the dom type?
https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts#L32-L54

**Comment by remusao** [comment]
Hi @dud3,

Apologies for the delay, I have been busy with other projects. I understand what you want to achieve now. There is no direct way to count how many DOM type rules matched because it would be expensive to do by default, but it's possible. Here is how I think about it:

The [`style-injected`](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer-example/index.ts#L52) event is triggered whenever the adblocker adds custom stylesheets to the page to hide ads. Because of the nature of these rules, it is not always possible to know which rules will actually have an effect once added to the page, so the adblocker makes its best guess at finding a very small subset of rules which have a high chance of hiding ads. So we inject a bunch of them, not all of which will actually be used.

The to know the exact count, you would need to do the following:
1. Listen to this event.
2. Split the `style` argument (first argument of the callback) into individual CSS selectors.
3. Try all of them against the page (maybe using the `page.$` Puppeteer API).
4. Count how many of them matched.

This might take a few hundreds of milliseconds (which would be too much overhead for the adblocker running in production, but might be fine if your use-case involves analyzing the effect of the adblocker on pages).

I hope this helps,
Best,

**Comment by remusao** [comment]
I have written a small prototype to demonstrate what I had in mind. This seems to work fine:
```typescript
blocker.on('style-injected', async (style: string, url: string) => {
  if (style) {
    // Style is of the form:
    //
    // <STYLESHEET 1>
    //
    // <STYLESHEET 2>
    //
    // ...
    //
    // Where each stylesheet has the format:
    //
    // selector1,
    // selector2,
    // selector3,
    // ...
    // selectorN { <Some CSS> }
    //
    // To get individual selectors we first split each stylesheet individually.
    // Then we split the stylesheet into its individual selectors.
    for (const stylesheet of style.split('}\n\n')) {
      const selectors = stylesheet.split(',\n');

      // Strip the '{ <Some CSS> }' part from last line.
      if (selectors.length !== 0) {
        const lastSelector = selectors[selectors.length - 1];
        const endOfLastSelector = lastSelector.lastIndexOf('{');
        if (endOfLastSelector !== -1) {
          selectors[selectors.length - 1] = lastSelector.slice(0, endOfLastSelector).trim();
        }
      }

      // Check each selector against the page.
      for (const selector of selectors) {
        if ((await page.$(selector)) !== null) {
          console.log('Got a matching selector:', selector);
        }
      }
    }
  }
});
```

**Comment by dud3** [comment]
Hi @remusao, 

No worries for the late response. :)

Thanks for the code snippet, appreciated.

**Comment by dud3** [comment]
Hi @remusao

Slightly off the topic of this issue, does this library detect popups?

E.x.:
![image](https://user-images.githubusercontent.com/5823644/100514008-9a9d5600-3171-11eb-92e4-bcfe6ff169f2.png)

**Comment by remusao** [comment]
Hi @dud3,

This kind of popup we should be able to block yes. The library supports the rules able to do that, but this does not mean that there are rules handling this particular website (It's relatively easy to create new rules to customize the behavior, though). Can you maybe share the domain/url so that I can check what's going on?

**Comment by dud3** [comment]
Hi @remusao 

Sure, here's the prototype: http://64.227.14.199/http-client (note: there's no url validation, so it requires http or https in front of the url, e.x.: https://cnn.com).

What I'm tying to achieve is to rate the site based on how many ads, trackers, key loggers, sessions recorders and popups (annoyance type of popups).

The only thing left popup detection.

Note: I'm quite new to the puppeteer and how adblockers or other type of blockers works, so excuse me for my silly questions. :)

Because of my lack of knowledge, I had a naïve idea on how to detect popups, let me know if it doesn't sound right.
Using puppeteer go through few of the internal links of a site and do nothing but scroll down or up and wait and check if the body scroller disappears, if so we can assume that a popup might have triggered, after which we can try to find an element with highest z-index and analyze the content?
In mobile mode would be more accurate I guess, since the mobile screen view is small and the vertical scrollbar almost always exits.

If you have a discord account and you don't mind it perhaps we can chat there.

Thank you.

**Comment by dud3** [comment]
Actually, I just did try my naïve idea and it seems not that accurate. :)

**Comment by remusao** [comment]
Feel free to hit me up at `remusao` on Discord if you'd like to discuss this.

**Comment by dud3** [comment]
Sent a friend request, mine is: nulldivinfinity#8745

**Comment by dud3** [comment]
Hi @remusao 

The following doesn't work, I guess enableBlockingInPage already is intercepting the requests.

How can I block images from the adblocker instead?

```await blocker.enableBlockingInPage(page);

          await page.setRequestInterception(true);

          page.on('request', async (request) => {
            console.log(request.resourceType() == 'image');

            try {
              switch (await request.resourceType()) {
                case "image":
                case "stylesheet":
                case "font":
                case "media":
                  await request.abort();
                  break;
                default:
                  await request.continue();
                  break;
              }
            } catch (e) {
              console.log(e);
            }
          });
```
