### ISSUE TITLE
Block in iframes

### ISSUE THREAD

**Issue by kaiserdj** [cliqz-oss/adblocker#1525]
Good morning,
First of all thank you very much for the project, it works really well, but I have a problem.

I've copied all the lists my uBlock Origin extension uses and added them to ElectronBlocker:
```
'https://easylist.to/easylist/easylist.txt',
//'https://easylist.to/easylist/easyprivacy.txt',
'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt',
'https://easylist.to/easylist/fanboy-social.txt',
'https://secure.fanboy.co.nz/fanboy-annoyance.txt',
'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt',
'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt',
//'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt',
'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt',
'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt',
'https://easylist.to/easylist/easylist.txt',
//'https://easylist.to/easylist/easyprivacy.txt',
'https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt',
'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext',
'https://filters.adtidy.org/extension/ublock/filters/9.txt',
'https://easylist-downloads.adblockplus.org/easylistspanish.txt',
```

I have tried to load the same pages that I load with my uBlock Origin, but it does not block the same things ... the problem is that there are some pages that generate infinite loops of new windows (it only happens when I have the ElectronBlocker).

Example url: `https://streamtape.com/e/r8kGrYyR1efM0P/`

Example iframe:
 ```
<iframe width="560" height="315" frameborder="0" src="https://streamtape.com/e/r8kGrYyR1efM0P/" scrolling="no" allowfullscreen=""></iframe>
```

**Comment by remusao** [comment]
Hi @kaiserdj,

Could you copy the snippet of code you use to initialize the blocker instance with all the lists so that I can run it on my side and reproduce the issue? It would be helpful to have a minimal script to start investigating.

Best,
Rémi

**Comment by remusao** [comment]
Hi @kaiserdj,

I did not have much time to investigate in depth but I was able to reproduce the issue. I suspect this might be an issue with Electron and not the lists (it happens with multiple selections of filters). I tried to add the `nodeIntegrationInSubFrames` option and it seemed to make a difference so it might be because the preload script is not injected in all iframes by default?

Could you confirm if starting Electron with the following options changes anything for you?
```js
mainWindow = new BrowserWindow({
  height: 600,
  width: 800,
  webPreferences: {
    contextIsolation: true,
    nodeIntegrationInSubFrames: true, // new
  },
});
```

**Comment by kaiserdj** [comment]
Hi @remusao ,
I have tried these options and I do not notice any type of change, it continues to act the same way.
Just in case, I have tried different pages and the same thing happens in all.

Anything you can help with, feel free to tell me and thank you very much

**Comment by remusao** [comment]
Hey @kaiserdj,

Appologies for the long time without an answer, I've been a bit busy on other projects lately. Is there any update on this from your side? From the last things I tried, I think this might be an issue specific to Electorn platform since I could not reproduce with the WebExtension blocker. There might be some issue with the way some APIs are used but I would need to investigate a bit.
