### ISSUE TITLE
How can I use this with "require" instead of "import"

### ISSUE THREAD

**Issue by ryankashi** [cliqz-oss/adblocker#1739]
I am looking for an electron adblocker implementation that is using "require." I see in the documentation that we can use this adblocker using ES6 import, however is there an implementation that uses "require" instead?

**Comment by remusao** [comment]
Hey @ryankashi,

Yes you can use the library with `require` instead of the `import` syntax. It should work as is. You can start from the example [here](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-electron-example/index.ts) and transform the imports to `require` (and remove Type annotations if you are not using TypeScript in your project).

I hope this helps,
