### ISSUE TITLE
Electron ^12.x support

### ISSUE THREAD

**Issue by Xanon50rus** [cliqz-oss/adblocker#1840]
I tried to update Electron 12.0.0 to 12.0.2 but got error:
`npm ERR! Could not resolve dependency:
npm ERR! peer electron@"^11.x" from @cliqz/adblocker-electron@1.20.4
npm ERR! node_modules/@cliqz/adblocker-electron
npm ERR!   @cliqz/adblocker-electron@"^1.20.4" from the root project`

Are there any plans to support version ^12.x?

**Comment by remusao** [comment]
Hey,

I would be up for updating to latest Electron but there are some breaking changes related to preload script isolation (they get their own isolated `window` object which is not the same as the one from the web page itself), which breaks some of the features of the adblocker (scriptlet injection for example). I had a quick look but it seemed like fixing would take some changes. Since I do not have much time to dedicate to this at the moment, I would love some support from the community (especially people who know the Electron ecosystem better than me) to address this.

Best,

**Comment by remusao** [comment]
Hey @sentialx,

I see you have updated Wexond to latest Electron [recently](https://github.com/wexond/browser-base/commit/d66fca7dbcc2edcf517f56914e58a525dd641795). I was wondering if you might have some insights about what it would take to update the adblocker as well, for now I think some of the features might be broken by Electron 12. I had a quick look a couple of weeks ago and the main issue seemed to be that the preload script now has its own window global instead of sharing it with the page itself. Do you know of a way to work around this limitation (i.e. how to access the page's window or inject stylesheets to the page itself instead of the preload's script?).

Currently we use `sender.insertCSS` when we receive a message from preload script, but in this case sender is the preload script itself, not the page. At this point we would need to be able to interact wit the page itself instead of the preload script. Code: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-electron/adblocker.ts#L257

**Comment by sentialx** [comment]
I think the `sender` property is perfectly fine and is related to the WebContents containing the web page. However, I think you're having issues with recent Electron changes to the `contextIsolation` property being `true` by default as of 12. It was created to prevent XSS attacks and accessing privileged APIs of the preload context, so the `window` object is separated. I think I didn't need to change anything in my code, because as you may know, I'm injecting the adblocker on my own, but I would suggest to use [`contextBridge`](https://www.electronjs.org/docs/api/context-bridge) module from Electron. This API allows you to expose APIs to the external context.

**Comment by remusao** [comment]
Thanks @sentialx. I've set `contextIsolation` to `false` but still cannot get this to work. For some reason the preload script seems to be injected into devtools (if they are opened with `openDevTools`) but not in the page loaded in the main window (either main frame or iframes). I am not sure how to go about debugging this.

**Comment by remusao** [comment]
Something fishy is happening, when I set the preload script at the `BrowserWindow` creation it works, but if I set it using `setPreloads()` (using the same absolute path) then it does not seem to be injected in the web content loaded in the window. Adding a setTimeout of 2 seconds does not seem to make a difference (I initially thought this might be a race, but this does not seem to be the case).

**Comment by remusao** [comment]
Weird, I got it to work but not 100% sure what was wrong. It seems like it might sometimes fail to add a preload script if we wait too long between creation of the window and the preload registration. I tried by adding an artificial timeout between there two events and this seemed to be enough to prevent the preload script to load properly.
