### ISSUE TITLE
Electron version requirements

### ISSUE THREAD

**Issue by Jelmerro** [cliqz-oss/adblocker#2224]
I have a question/report about the Electron versions specified in the package.json file. I am using Electron 15, and it keeps mentioning that the adblocker is not compatible based on the dependencies in the file. Is this actually the case, or do we simply need to update the versions? I can confirm that most of the blocking functionality works, even the cosmetic filtering, although I do occasionally see an error in the webview developer tools (this is fairly rare). I would suggest to either update the versions more often, or change it to accept any version of Electron and keep the package working with the latest Electron stable. Though feel free to close this issue if neither of those solutions would work for this package.

**Comment by remusao** [comment]
Hi @Jelmerro,

Long time no see! :) Usually, I bump the Electron version range from package.json when a new stable version is released (I see that the v15 is still in beta?). The reason is that I like to make sure the breaking changes introduced by major versions do not break features of the adblocker (although with v15 that does not seem to be the case, from your experience). In the meantime, I think you could force the installation of `@cliqz/adblocker` with a "non supported" version of Electron? (I forgot how but I think that's possible with npm/yarn).

I hope this helps,
Rémi

**Comment by Jelmerro** [comment]
No need to make issues if the adblocker works as good as it does, at leas until this small annoyance ;) 

I think it's better to accept more and possibly any Electron version (with a minimum I guess), because otherwise it's not possible to install this plugin without `--force`, which is a bit weird. I know Electron 15 is still in beta, but it will be leaving that next week, and 14 is already the main stable which is also indicated as "unsupported" by the adblocker package. So to make it possible to install this without having to force the installation it would be nice to just set a minimum version that's supported and expect it to continue working, at least until you see new issues on github of users trying it in a beta/nightly.

**Comment by remusao** [comment]
I see, that makes sense. Would you be willing to make a PR with this change? I guess this would need to be modified: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-electron/package.json#L37

**Comment by Jelmerro** [comment]
Done, I hope that the new definition does this, but I can't really test it since unless it's published as a package and stored as a dependency in a project.

**Comment by remusao** [comment]
Thanks again, let me know if this works better with [v1.22.6](https://github.com/cliqz-oss/adblocker/releases/tag/v1.22.6).

**Comment by Jelmerro** [comment]
It does work in the usual sense that you can now install stable versions, but apparently it's impossible to make this possible for pre-release versions, as can be seen [in this stackoverflow thread](https://stackoverflow.com/questions/67934358/npm-including-all-range-of-pre-release-when-defining-peer-dependency). I have tried it with `>=11.x.x-alpha || >=12.x.x-alpha` and so for, both even that doesn't work for alpha or beta versions of 15, so I'm afraid this is the best we can do, at least it's a bit better than before, but it doesn't completely solve it for me sadly. Depending on how you do things in this repo, we could close this issue as solved, as it's a problem of npm that this can't be further improved.

**Comment by remusao** [comment]
Since it is not clear that there will be a fix for this I would probably close the issue, people coming for the same issue will find this issue and the state of it. I think the change you contributed is already an improvement regarding the initial problem, and if people want to test alpha/beta can use `npm install --force` to ignore the warning.

Thanks again for all the time you spent investigating and opening the PR with the fix! Much appreciated.

**Comment by Jelmerro** [comment]
I agree, glad we could work on improving the package together like this. Just want to mention that we probably want to make the same change [here](https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-electron-preload/package.json#L36), which I didn't notice when working on the code initially.

Finally, it's also an option to do `npm install --legacy-peer-deps`, which is less aggressive than using `--force`.

**Comment by remusao** [comment]
Good point! I forgot we had the same version bound in this other package.
