### ISSUE TITLE
add Javascript rules syntax (#%#，#@%#）

### ISSUE THREAD

**Issue by sysnpc** [cliqz-oss/adblocker#297]
Hi,  thanks for creating this awesome project!

I am using it in electron project。
I have a problem, I want to inject custom javascript into the page, it doesn't seem to be enough at present。

`script:inject(...)` Limited use of special scripts.

hope to add `#%#` and `#%@#` support.
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules

**Comment by remusao** [comment]
Hi @sysnpc and sorry for the late response,

Did I understand correctly that you would like to inject your own custom rules and having the `#%#` and `#%@#` syntax supported would solve this use-case? Or do you want to add some AdGuard list in the adblocker?

For the former, I have mixed feelings about supporting this syntax (although it should not be hard to do) since it allows arbitrary JavaScript to be injected using simple filters that can be fetched from un-trusted source. In the current model you have to add a custom resource and then use a filter such as `##+js(scriptname)` (or legacy syntax: `##script:inject(scriptname)`) which references this resource. One way which you could solve this currently if you want to inject custom scripts would be something like (API is not nice but can be improved):

```js
import { ElectronBlocker } from `@cliqz/adblocker-electron`;

(async () => {
  const blocker = await ElectronBlocker.fromPrebuiltAdsAndTracking();

  // Add a custom script injection
  blocker.resources.js.set('custom-script.js', 'window.__gaq = undefined;');

  // Add a new rule which will inject this particular script on 'example.org' pages
  blocker.updateFromDiff({
    added: ['example.org##+js(custom-script.js)'],
  });
})();
```

I am currently working on improving resources management and this would be a good opportunity to create a better API for this particular use-case. If this does not satisfy your use-case then maybe we can add support for `#%#` and `#%@#` but that would not be my preferred solution for the problem at hand.

I hope that helps,
Rémi

**Comment by sysnpc** [comment]
It is helpful to me. thank you very much.

**Comment by remusao** [comment]
I am closing this issue. Feel free to re-open it or open a new one if you need anything else.
