### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by lincolnaleixo** [cliqz-oss/adblocker#389]
I'm getting this error when running with electron
I'm doing something wrong? I'm placing this app.one('ready'):

```
WebExtensionBlocker.fromPrebuiltAdsAndTracking().then(blocker => {
    blocker.enableBlockingInBrowser();
  });
```

**Comment by remusao** [comment]
Hey @lincolnaleixo,

The issue is that `fetch` is not a global in Electron context. I would recommend that you install either `cross-fetch` or `node-fetch` and pass that as first argument of `fromPrebuiltAdsAndTracking`. Also, if you want to block ads in Electron, you will need to use the package `@cliqz/adblocker-electron` (I see from your code snippet that you use the webextension version, which only works for Firefox or Chrome integration). That would look something like:

```js
const { ElectronBlocker } = require('@cliqz/adblocker-electron');
const fetch = require('node-fetch');

ElectronBlocker.fromPrebuiltAdsAndTracking(fetch).then(blocker => {
  blocker.enableBlockingInSession(yourSession);
});
```

For more details you can check the [README](https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-electron#usage) of `@cliqz/adblocker-electron` and check the example project:https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-electron-example

**Comment by lincolnaleixo** [comment]
thanks @remusao . I've changed to you ElectronBlocker. 
Is this supposed to work for webview as well? I'm not getting any block when accessing sites from webview

**Comment by remusao** [comment]
It should work yes. Would you maybe be able to share the code you are working on here? I think it would be easier for me to diagnose the issue.

**Comment by lincolnaleixo** [comment]
Sure, thanks for helping me out!

This I have on main.js inside app.on:
  ```
 if (session.defaultSession === undefined) {
    throw new Error('defaultSession is undefined');
  }
const blocker = await ElectronBlocker.fromPrebuiltAdsAndTracking(fetch, {
    enableCompression: true
  });
  blocker.enableBlockingInSession(session.defaultSession);

  blocker.on('request-blocked', request => {
    console.log('blocked', request.tabId, request.url);
  });

  blocker.on('request-redirected', request => {
    console.log('redirected', request.tabId, request.url);
  });

  blocker.on('request-whitelisted', request => {
    console.log('whitelisted', request.tabId, request.url);
  });

  blocker.on('csp-injected', request => {
    console.log('csp', request.url);
  });

  blocker.on('script-injected', (script, url) => {
    console.log('script', script.length, url);
  });

  blocker.on('style-injected', (style, url) => {
    console.log('style', style.length, url);
  });
```

index.html:

```
<html>
  <head>
    <link rel="stylesheet" href="reset.css" />
  </head>
  <body style="-webkit-app-region: drag">
    <webview
      allowpopups="false"
      webpreferences="allowRunningInsecureContent, javascript=yes"
      partition="persist:github"
      id="foo"
      src="about:blank"
      style="display:inline-flex; width:0px; height:0px"
    ></webview>
    <script src="./renderer.js"></script>
  </body>
</html>
```
And I've just a simple dom-ready event on renderer.js:

```
webview.addEventListener('dom-ready', async () => {
  if (firstLoad) {
    webview.loadURL('http://www.youtube.com');
  }
  webview.style.width = '100%';
  webview.style.height = '100%';
});
```

For example, youtube videos are getting ads

**Comment by remusao** [comment]
Thanks for the snippets. Unfortunately I am not even able to load the `webview` correctly locally (without any content blocking). They mention in the [official documentation](https://electronjs.org/docs/api/webview-tag#warning) that this feature is unstable:

> Electron's webview tag is based on Chromium's webview, which is undergoing dramatic architectural changes. This impacts the stability of webviews, including rendering, navigation, and event routing. We currently recommend to not use the webview tag and to consider alternatives, like iframe, Electron's BrowserView, or an architecture that avoids embedded content altogether.

Here is what I have, maybe you can help me have a minimal self-contained example.

*main.js*
```js
const { app, BrowserWindow } = require('electron');

let mainWindow;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({ width: 1024, height: 768, webviewTag: true });
  mainWindow.loadURL('file://' + __dirname + '/index.html');
  mainWindow.openDevTools();
});
```

*index.html*:
```html
<html>
  <head> </head>
  <body>
    <webview
      id="foo"
      src="https://youtube.com/"
      style="display:inline-flex; width:100%; height:100%;"
    ></webview>
  </body>
</html>
```

I removed the `renderer.js` for now since I wanted a really minimal working example of a webview but so far I had no luck with that. When I start the app it just displays a blank page.

**Comment by lincolnaleixo** [comment]
The tag _webviewTag_ must be inside {webPreferences} object (https://electronjs.org/docs/api/browser-window#new-browserwindowoptions):

```
mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    webPreferences: {
      webviewTag: true
    }
  });
```

**Comment by remusao** [comment]
@lincolnaleixo Thanks, good catch. I did not read the documentation with enough attention! So I could get it working with a fairly minimal examples and ads are blocked. Here is the code I have:

*main.js*
```js
const { app, BrowserWindow, session } = require('electron');
const { ElectronBlocker } = require('@cliqz/adblocker-electron');
const fetch = require('node-fetch');

app.on('window-all-closed', () => { app.quit(); });

app.on('ready', async () => {
  const mainWindow = new BrowserWindow({ webPreferences: { webviewTag: true } });
  (await ElectronBlocker.fromPrebuiltAdsAndTracking(fetch)).enableBlockingInSession(
    session.defaultSession,
  );
  mainWindow.loadURL('file://' + __dirname + '/index.html');
});
```

*index.html*
```html
<html>
  <head></head>
  <body>
    <webview
      src="https://youtube.com/"
      style="display:inline-flex; width:100%; height:100%;"
    ></webview>
  </body>
</html>
```

Something that might make a difference is that I wait for blocker to be initialized before navigating to `https://youtube.com`. Otherwise it could be that for the first requests the adblocker is not ready yet.

**Comment by lincolnaleixo** [comment]
The await did the trick, thank you for the help!
