### ISSUE TITLE
Add option to whitelist website from adblocking but not from anti tracking

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [cliqz-oss/adblocker#461]
I posted this issue on the Ghostery section but I think it also corresponds to the adblocker section

https://github.com/ghostery/ghostery-extension/issues/493

**Comment by remusao** [comment]
@Lucas-Di-Tomase, thanks for reporting this issue, it makes a lot of sense. Though, I would rather keep the product-specific discussions related to Ghostery on the `ghostery-extension` repository. This `cliqz-oss/adblocker` repository should focus on the core adblocking mechanism itself and related issues: _ads not blocked or breakage_. Since the library is used across multiple products as well as open-source projects it would be desirable to continue this discussion on the first issue you opened: https://github.com/ghostery/ghostery-extension/issues/493

Since this feature request is a product decision, I think @christophertino will take it from here.
