### ISSUE TITLE
Electron 9 cosmetic filtering stops working on some sites

### ISSUE THREAD

**Issue by Jelmerro** [cliqz-oss/adblocker#573]
When visiting certain websites with the electron version of this project, I get this error:
```
Uncaught Error: An object could not be cloned.
    at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.send (electron/js2c/renderer_init.js:1034)
    at ../node_modules/@cliqz/adblocker-electron-preload/dist/preload.cjs.js:156
```
This for example happens on youtube.com, but I have seen it on a handful of other websites.
It is caused by this https://www.electronjs.org/docs/breaking-changes#sending-non-js-objects-over-ipc-now-throws-an-exception breaking change in Electron 9.

It seems that sometimes DOM elements are send in the hrefs list, which can not be serialized.
![image](https://user-images.githubusercontent.com/1696674/75923268-0235a780-5e65-11ea-9e23-3802285e486f.png)

**Comment by remusao** [comment]
Hi @Jelmerro,

Nice catch, this should definitely not happen and only strings should be sent, I am a bit short on time at the moment but will try to have a look. Otherwise, if you would be willing to produce a fix for this issue I would be more than happy to guide you. First guess would be that some checks need to be added around this line: https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-content/adblocker.ts#L68
