### ISSUE TITLE
Ghostery breaks youtube on firefox.

### ISSUE THREAD

**Issue by Rtizer-9** [cliqz-oss/adblocker#646]
I'm on firefox nightly 76.0a1

Ghostery is not allowing youtube videos to load. All the features: adblock, anti-tracking and smart-blocking is on.

Can you please make your changelogs more detailed for ghostery, ghostery-start-tab and cliqz.

What's really the difference between ghostery start tab and cliqz-tab?

Also,please make the broken-page reporting less cumbersome, look the implementation of I don't care about cookies.

**Comment by remusao** [comment]
Hi @Rtizer-9,

I have been investigating the issue and traced it back to a defect in our filters builder and deployer (it had some issue last night and could not deploy updates to all users as usual). The issue has been fixed and deployer is running as I write these lines, which should fix this particular issue. The update might take up to an hour to reach you (updates are checked automatically once per hour in Ghostery). I will update this issue once I was able to confirm that the issue is 100% fixed.

Thanks for your patience,

**Comment by Rtizer-9** [comment]
Thanks for quick response.

**Comment by remusao** [comment]
@Rtizer-9 I have checked that the issue is now fixed, you should get the update automatically in up to one hour, or if you restart your Ghostery extension (or browser).

**Comment by Rtizer-9** [comment]
I just restarted the browser and even after disabling ghostery I had the same error. I disabled ublock-origin and the error was gone. On front page surprisingly ads are their even though both ublock-origin and ghostery is installed.

I recently read a post on reddit I think, where people were reporting that youtube has found some way to circumvent adblockers. I think this maybe part of that. Let's see what solution adblockers come up with.

Closing it for now.
Please give some attention to the other requests in the first comment.

Thanks

**Comment by remusao** [comment]
> I recently read a post on reddit I think, where people were reporting that youtube has found some way to circumvent adblockers. I think this maybe part of that. Let's see what solution adblockers come up with.

Yes correct, things changed in the last few days on YouTube and some rules needed to be adjusted to continue blocking ads.

 > Please give some attention to the other requests in the first comment.

Could you maybe update your issue opened on `browser-core`? I think someone will answer to the other issues there since they are not adblocker-related.

Thanks again,
Best,

**Comment by Rtizer-9** [comment]
Sure.
