### ISSUE TITLE
Using adblock with request handle will throw errors

### ISSUE THREAD

**Issue by Truth1984** [cliqz-oss/adblocker#994]
Here is what I did :
```js
// init a browser; 
// init a page
let result = parseFromFiles();
PuppeteerBlocker.parse(result).enableBlockingInPage(page);
page.setRequestInterception(true);
page.on("request", async (request) => {
// request handled by middlewares, will abort if any returns false
    requestMiddlewares(request) ?  request.continue() : request.abort();
  });
```

Here is the response of general request handling: https://github.com/puppeteer/puppeteer/issues/4524#issuecomment-499330337

Thus, when using your package and this setup will throw `Error: Request is already handled`.
and I wonder if you have any suggestions on fixing this issue? Like provide a middleware for handling the result and let users to decide if they want to abort it or not ?

**Comment by remusao** [comment]
Hi @Truth1984,

At the moment, because of limitations of Puppeteer it's a bit cumbersome to use both the adblocker and custom request handlers. It's possible, though, using some tricks I described in another issue: https://github.com/cliqz-oss/adblocker/issues/493#issuecomment-585873954

```typescript
import { PuppeteerBlocker } from '@cliqz/adblocker-puppeteer';

// await page.setRequestInterception(true);

PuppeteerBlocker.fromPrebuiltAdsAndTracking(fetch).then((blocker) => {
  page.on('domcontentloaded', (frame) => blocker.onFrameNavigated(page.mainFrame()));
  page.on('frameattached', (frame) => blocker.onFrameNavigated(frame));
  page.on('request', (request) => {
    const { redirect, match } = blocker.match(fromPuppeteerDetails(request));

    if (redirect !== undefined) {
      request.respond({
        body: redirect.body,
        contentType: redirect.contentType,
      });
    } else if (match === true) {
      request.abort('blockedbyclient');
    } else {
      // ---------------------------------- //
      // TODO - do something with 'request' //
      // ---------------------------------- //
      request.continue();
    }
  });
});
```

Alternatively, I am working on a 'request pipeline' abstraction at the moment to allow registering multiple blocking listeners easily in Puppeteer/Electron/Playwright/Browser. You can see the progress in this issue: https://github.com/cliqz-oss/adblocker/issues/811

I hope this helps,
Rémi

**Comment by Truth1984** [comment]
feeling a bit shaky.
I can remove listener even I don't have them, but when I tried to disable the blocking it throws `Error: Trying to disable blocking which was not enabled`.

Thanks though.

**Comment by remusao** [comment]
I agree, this is clearly not ideal at the moment and I hope the proposal from #811 can make things much nicer! I will try to push it forward in the following days.
